---
version: '3.5'

services:
  jmeter:
    image: justb4/jmeter
    network_mode: "host"
    command: "-Dlog_level.jmeter=DEBUG -n -t /cch_portal_test.jmx -l /test_results/cch_portal_test.jtl -j /test_results/jmeter.log -e -o /test_results/report"
    volumes:
      - type: bind
        source: ./coastal-hazards-integration-testing/cch_portal_test.jmx
        target: /cch_portal_test.jmx
      - type: bind
        source: ./coastal-hazards-integration-testing/test_results/
        target: /test_results
      - type: bind
        source: ./coastal-hazards-integration-testing/test_data/
        target: /test_data