---
version: '3.7'

services:
  cch_postgres:
    build:
      # Build context for this image is set to its sub-directory
      dockerfile: Dockerfile.remote

  cch_n52_wps:
    build:
      # Build context for this image is set to project root directory
      dockerfile: ./coastal-hazards-n52/Dockerfile.remote

  cch_portal:
    build:
      # Build context for this image is set to project root directory
      dockerfile: ./coastal-hazards-portal/Dockerfile.remote

  cch_geoserver:
    build:
      # Build context for this image is set to project root directory
      dockerfile: ./coastal-hazards-geoserver/Dockerfile.remote
